// Code generated by MockGen. DO NOT EDIT.
// Source: member_dao.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/tomoffice/go-clean-architecture/internal/modules/member/interface_adapter/dao"
	pagination "github.com/tomoffice/go-clean-architecture/internal/shared/pagination"
)

// MockMemberDAO is a mock of MemberDAO interface.
type MockMemberDAO struct {
	ctrl     *gomock.Controller
	recorder *MockMemberDAOMockRecorder
}

// MockMemberDAOMockRecorder is the mock recorder for MockMemberDAO.
type MockMemberDAOMockRecorder struct {
	mock *MockMemberDAO
}

// NewMockMemberDAO creates a new mock instance.
func NewMockMemberDAO(ctrl *gomock.Controller) *MockMemberDAO {
	mock := &MockMemberDAO{ctrl: ctrl}
	mock.recorder = &MockMemberDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberDAO) EXPECT() *MockMemberDAOMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockMemberDAO) CountAll(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockMemberDAOMockRecorder) CountAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockMemberDAO)(nil).CountAll), ctx)
}

// Create mocks base method.
func (m_2 *MockMemberDAO) Create(ctx context.Context, m *dao.MemberRecord) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMemberDAOMockRecorder) Create(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberDAO)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockMemberDAO) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMemberDAOMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemberDAO)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockMemberDAO) GetAll(ctx context.Context, p pagination.Pagination) ([]*dao.MemberRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, p)
	ret0, _ := ret[0].([]*dao.MemberRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMemberDAOMockRecorder) GetAll(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMemberDAO)(nil).GetAll), ctx, p)
}

// GetByEmail mocks base method.
func (m *MockMemberDAO) GetByEmail(ctx context.Context, email string) (*dao.MemberRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*dao.MemberRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockMemberDAOMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockMemberDAO)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockMemberDAO) GetByID(ctx context.Context, id int) (*dao.MemberRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dao.MemberRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMemberDAOMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMemberDAO)(nil).GetByID), ctx, id)
}

// UpdateEmail mocks base method.
func (m *MockMemberDAO) UpdateEmail(ctx context.Context, id int, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, id, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockMemberDAOMockRecorder) UpdateEmail(ctx, id, newEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockMemberDAO)(nil).UpdateEmail), ctx, id, newEmail)
}

// UpdatePassword mocks base method.
func (m *MockMemberDAO) UpdatePassword(ctx context.Context, id int, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockMemberDAOMockRecorder) UpdatePassword(ctx, id, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockMemberDAO)(nil).UpdatePassword), ctx, id, newPassword)
}

// UpdateProfile mocks base method.
func (m_2 *MockMemberDAO) UpdateProfile(ctx context.Context, m *dao.MemberRecord) (*dao.MemberRecord, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateProfile", ctx, m)
	ret0, _ := ret[0].(*dao.MemberRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockMemberDAOMockRecorder) UpdateProfile(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockMemberDAO)(nil).UpdateProfile), ctx, m)
}
