// Code generated by MockGen. DO NOT EDIT.
// Source: member_persistence.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "github.com/tomoffice/go-clean-architecture/internal/modules/member/entity"
	pagination "github.com/tomoffice/go-clean-architecture/internal/shared/pagination"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemberPersistence is a mock of MemberPersistence interface.
type MockMemberPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockMemberPersistenceMockRecorder
}

// MockMemberPersistenceMockRecorder is the mock recorder for MockMemberPersistence.
type MockMemberPersistenceMockRecorder struct {
	mock *MockMemberPersistence
}

// NewMockMemberPersistence creates a new mock instance.
func NewMockMemberPersistence(ctrl *gomock.Controller) *MockMemberPersistence {
	mock := &MockMemberPersistence{ctrl: ctrl}
	mock.recorder = &MockMemberPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberPersistence) EXPECT() *MockMemberPersistenceMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockMemberPersistence) CountAll(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockMemberPersistenceMockRecorder) CountAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockMemberPersistence)(nil).CountAll), ctx)
}

// Create mocks base method.
func (m_2 *MockMemberPersistence) Create(ctx context.Context, m *entity.Member) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMemberPersistenceMockRecorder) Create(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberPersistence)(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m *MockMemberPersistence) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMemberPersistenceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemberPersistence)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockMemberPersistence) GetAll(ctx context.Context, pagination pagination.Pagination) ([]*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, pagination)
	ret0, _ := ret[0].([]*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMemberPersistenceMockRecorder) GetAll(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMemberPersistence)(nil).GetAll), ctx, pagination)
}

// GetByEmail mocks base method.
func (m *MockMemberPersistence) GetByEmail(ctx context.Context, email string) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockMemberPersistenceMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockMemberPersistence)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockMemberPersistence) GetByID(ctx context.Context, id int) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMemberPersistenceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMemberPersistence)(nil).GetByID), ctx, id)
}

// UpdateEmail mocks base method.
func (m *MockMemberPersistence) UpdateEmail(ctx context.Context, id int, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, id, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockMemberPersistenceMockRecorder) UpdateEmail(ctx, id, newEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockMemberPersistence)(nil).UpdateEmail), ctx, id, newEmail)
}

// UpdatePassword mocks base method.
func (m *MockMemberPersistence) UpdatePassword(ctx context.Context, id int, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockMemberPersistenceMockRecorder) UpdatePassword(ctx, id, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockMemberPersistence)(nil).UpdatePassword), ctx, id, newPassword)
}

// UpdateProfile mocks base method.
func (m_2 *MockMemberPersistence) UpdateProfile(ctx context.Context, m *entity.Member) (*entity.Member, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateProfile", ctx, m)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockMemberPersistenceMockRecorder) UpdateProfile(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockMemberPersistence)(nil).UpdateProfile), ctx, m)
}
