// Code generated by ent, DO NOT EDIT.

package ent

import (
	"module-clean/internal/modules/member/driver/persistence/ent/member"
	"module-clean/internal/modules/member/driver/persistence/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescName is the schema descriptor for name field.
	memberDescName := memberFields[0].Descriptor()
	// member.NameValidator is a validator for the "name" field. It is called by the builders before save.
	member.NameValidator = memberDescName.Validators[0].(func(string) error)
	// memberDescPassword is the schema descriptor for password field.
	memberDescPassword := memberFields[2].Descriptor()
	// member.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	member.PasswordValidator = memberDescPassword.Validators[0].(func(string) error)
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberFields[3].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
}
