app_name: "go-clean-architecture"
env: dev
server:
  http:
    host: "0.0.0.0"
    port: "80"
database:
  dsn: "file:./data/identifier.sqlite?cache=shared"
auth:
  jwt:
    algorithm: "HS256"
    secret: "your_jwt_secret"
    expire: 3600
logger:
  console:
    enabled: true
    level: "debug"
    format: "console"
  gcp:
    enabled: false
    project_id: ""
    level: "info"
  seq:
    enabled: false
    endpoint: "http://localhost:5341"
    api_key: ""
    level: "info"
    console_output_enabled: false