// Code generated by MockGen. DO NOT EDIT.
// Source: member_presenter.go

// Package mock is a generated GoMock package.
package mock

import (
	entity "module-clean/internal/modules/member/entity"
	output "module-clean/internal/modules/member/interface_adapter/outputmodel"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemberPresenter is a mock of MemberPresenter interface.
type MockMemberPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockMemberPresenterMockRecorder
}

// MockMemberPresenterMockRecorder is the mock recorder for MockMemberPresenter.
type MockMemberPresenterMockRecorder struct {
	mock *MockMemberPresenter
}

// NewMockMemberPresenter creates a new mock instance.
func NewMockMemberPresenter(ctrl *gomock.Controller) *MockMemberPresenter {
	mock := &MockMemberPresenter{ctrl: ctrl}
	mock.recorder = &MockMemberPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberPresenter) EXPECT() *MockMemberPresenterMockRecorder {
	return m.recorder
}

// PresentBindingError mocks base method.
func (m *MockMemberPresenter) PresentBindingError(err error) (int, output.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentBindingError", err)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(output.ErrorResponse)
	return ret0, ret1
}

// PresentBindingError indicates an expected call of PresentBindingError.
func (mr *MockMemberPresenterMockRecorder) PresentBindingError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentBindingError", reflect.TypeOf((*MockMemberPresenter)(nil).PresentBindingError), err)
}

// PresentCreateMember mocks base method.
func (m *MockMemberPresenter) PresentCreateMember(member *entity.Member) output.CreateMemberResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentCreateMember", member)
	ret0, _ := ret[0].(output.CreateMemberResponse)
	return ret0
}

// PresentCreateMember indicates an expected call of PresentCreateMember.
func (mr *MockMemberPresenterMockRecorder) PresentCreateMember(member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentCreateMember", reflect.TypeOf((*MockMemberPresenter)(nil).PresentCreateMember), member)
}

// PresentDeleteMember mocks base method.
func (m *MockMemberPresenter) PresentDeleteMember(member *entity.Member) output.DeleteMemberResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentDeleteMember", member)
	ret0, _ := ret[0].(output.DeleteMemberResponse)
	return ret0
}

// PresentDeleteMember indicates an expected call of PresentDeleteMember.
func (mr *MockMemberPresenterMockRecorder) PresentDeleteMember(member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentDeleteMember", reflect.TypeOf((*MockMemberPresenter)(nil).PresentDeleteMember), member)
}

// PresentGetMemberByEmail mocks base method.
func (m *MockMemberPresenter) PresentGetMemberByEmail(member *entity.Member) output.GetMemberByEmailResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentGetMemberByEmail", member)
	ret0, _ := ret[0].(output.GetMemberByEmailResponse)
	return ret0
}

// PresentGetMemberByEmail indicates an expected call of PresentGetMemberByEmail.
func (mr *MockMemberPresenterMockRecorder) PresentGetMemberByEmail(member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentGetMemberByEmail", reflect.TypeOf((*MockMemberPresenter)(nil).PresentGetMemberByEmail), member)
}

// PresentGetMemberByID mocks base method.
func (m *MockMemberPresenter) PresentGetMemberByID(member *entity.Member) output.GetMemberByIDResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentGetMemberByID", member)
	ret0, _ := ret[0].(output.GetMemberByIDResponse)
	return ret0
}

// PresentGetMemberByID indicates an expected call of PresentGetMemberByID.
func (mr *MockMemberPresenterMockRecorder) PresentGetMemberByID(member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentGetMemberByID", reflect.TypeOf((*MockMemberPresenter)(nil).PresentGetMemberByID), member)
}

// PresentListMembers mocks base method.
func (m *MockMemberPresenter) PresentListMembers(members []*entity.Member, total int) output.ListMemberResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentListMembers", members, total)
	ret0, _ := ret[0].(output.ListMemberResponse)
	return ret0
}

// PresentListMembers indicates an expected call of PresentListMembers.
func (mr *MockMemberPresenterMockRecorder) PresentListMembers(members, total interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentListMembers", reflect.TypeOf((*MockMemberPresenter)(nil).PresentListMembers), members, total)
}

// PresentUpdateMember mocks base method.
func (m *MockMemberPresenter) PresentUpdateMember(member *entity.Member) output.UpdateMemberResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentUpdateMember", member)
	ret0, _ := ret[0].(output.UpdateMemberResponse)
	return ret0
}

// PresentUpdateMember indicates an expected call of PresentUpdateMember.
func (mr *MockMemberPresenterMockRecorder) PresentUpdateMember(member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentUpdateMember", reflect.TypeOf((*MockMemberPresenter)(nil).PresentUpdateMember), member)
}

// PresentUseCaseError mocks base method.
func (m *MockMemberPresenter) PresentUseCaseError(err error) (int, output.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentUseCaseError", err)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(output.ErrorResponse)
	return ret0, ret1
}

// PresentUseCaseError indicates an expected call of PresentUseCaseError.
func (mr *MockMemberPresenterMockRecorder) PresentUseCaseError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentUseCaseError", reflect.TypeOf((*MockMemberPresenter)(nil).PresentUseCaseError), err)
}

// PresentValidationError mocks base method.
func (m *MockMemberPresenter) PresentValidationError(err error) (int, output.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentValidationError", err)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(output.ErrorResponse)
	return ret0, ret1
}

// PresentValidationError indicates an expected call of PresentValidationError.
func (mr *MockMemberPresenterMockRecorder) PresentValidationError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentValidationError", reflect.TypeOf((*MockMemberPresenter)(nil).PresentValidationError), err)
}
