// Code generated by MockGen. DO NOT EDIT.
// Source: member_input_port.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "module-clean/internal/modules/member/entity"
	inputmodel "module-clean/internal/modules/member/interface_adapter/inputmodel"
	pagination "module-clean/internal/shared/common/pagination"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemberInputPort is a mock of MemberInputPort interface.
type MockMemberInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockMemberInputPortMockRecorder
}

// MockMemberInputPortMockRecorder is the mock recorder for MockMemberInputPort.
type MockMemberInputPortMockRecorder struct {
	mock *MockMemberInputPort
}

// NewMockMemberInputPort creates a new mock instance.
func NewMockMemberInputPort(ctrl *gomock.Controller) *MockMemberInputPort {
	mock := &MockMemberInputPort{ctrl: ctrl}
	mock.recorder = &MockMemberInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberInputPort) EXPECT() *MockMemberInputPortMockRecorder {
	return m.recorder
}

// DeleteMember mocks base method.
func (m *MockMemberInputPort) DeleteMember(ctx context.Context, id int) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", ctx, id)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockMemberInputPortMockRecorder) DeleteMember(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockMemberInputPort)(nil).DeleteMember), ctx, id)
}

// GetMemberByEmail mocks base method.
func (m *MockMemberInputPort) GetMemberByEmail(ctx context.Context, email string) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberByEmail indicates an expected call of GetMemberByEmail.
func (mr *MockMemberInputPortMockRecorder) GetMemberByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberByEmail", reflect.TypeOf((*MockMemberInputPort)(nil).GetMemberByEmail), ctx, email)
}

// GetMemberByID mocks base method.
func (m *MockMemberInputPort) GetMemberByID(ctx context.Context, id int) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberByID", ctx, id)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberByID indicates an expected call of GetMemberByID.
func (mr *MockMemberInputPortMockRecorder) GetMemberByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberByID", reflect.TypeOf((*MockMemberInputPort)(nil).GetMemberByID), ctx, id)
}

// ListMembers mocks base method.
func (m *MockMemberInputPort) ListMembers(ctx context.Context, pagination pagination.Pagination) ([]*entity.Member, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, pagination)
	ret0, _ := ret[0].([]*entity.Member)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMemberInputPortMockRecorder) ListMembers(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMemberInputPort)(nil).ListMembers), ctx, pagination)
}

// RegisterMember mocks base method.
func (m *MockMemberInputPort) RegisterMember(ctx context.Context, member *entity.Member) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterMember", ctx, member)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterMember indicates an expected call of RegisterMember.
func (mr *MockMemberInputPortMockRecorder) RegisterMember(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMember", reflect.TypeOf((*MockMemberInputPort)(nil).RegisterMember), ctx, member)
}

// UpdateMember mocks base method.
func (m *MockMemberInputPort) UpdateMember(ctx context.Context, patch *inputmodel.PatchUpdateMemberInputModel) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", ctx, patch)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockMemberInputPortMockRecorder) UpdateMember(ctx, patch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockMemberInputPort)(nil).UpdateMember), ctx, patch)
}
