// Code generated by MockGen. DO NOT EDIT.
// Source: sender.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	logrus "github.com/sirupsen/logrus"
	zapcore "go.uber.org/zap/zapcore"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendLevel mocks base method.
func (m *MockSender) SendLevel(level zapcore.Level, msg string, fields logrus.Fields) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLevel", level, msg, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLevel indicates an expected call of SendLevel.
func (mr *MockSenderMockRecorder) SendLevel(level, msg, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLevel", reflect.TypeOf((*MockSender)(nil).SendLevel), level, msg, fields)
}
